version: '3.4'

services:
  todoapi:
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: TodoApi/Dockerfile
    depends_on: 
      - sqlserver

  sqlserver:
    container_name: SqlServer2022
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Devel0pm3nt
    ports:
      - "1433:1433"  # Map port 1433 on the host to port 1433 in the container
