@TodoApi_HostAddress = https://localhost:7170
@ApiKey = X7k0WSauhPDYEwz7

POST {{TodoApi_HostAddress}}/todoitems
X-API-KEY: {{ApiKey}}
Content-Type: application/json

{
    "name":"Send post 3",
    "isComplete": false
}


###

GET {{TodoApi_HostAddress}}/todoitems
X-API-KEY: {{ApiKey}}
###

GET {{TodoApi_HostAddress}}/todoitems/1
X-API-KEY: {{ApiKey}}

###

PUT {{TodoApi_HostAddress}}/todoitems/1
X-API-KEY: {{ApiKey}}
Content-Type: application/json

{
    "name":"Test post",
    "isComplete": false
}

###

DELETE {{TodoApi_HostAddress}}/todoitems/11
X-API-KEY: {{ApiKey}}

###

GET {{TodoApi_HostAddress}}/todoitems/complete
X-API-KEY: {{ApiKey}}

###

GET {{TodoApi_HostAddress}}/health

###

GET {{TodoApi_HostAddress}}/weather/Sydneys

###
