@TodoApi_HostAddress = https://localhost:7170


POST {{TodoApi_HostAddress}}/todoitems
X-API-KEY: C2BAECE9CE7748F7
Content-Type: application/json

{
    "name":"Send post 3",
    "isComplete": true
}


###

GET {{TodoApi_HostAddress}}/todoitems
X-API-KEY: C2BAECE9CE7748F7
###

GET {{TodoApi_HostAddress}}/todoitems/2
X-API-KEY: C2BAECE9CE7748F7

###

PUT {{TodoApi_HostAddress}}/todoitems/2
X-API-KEY: C2BAECE9CE7748F7
Content-Type: application/json

{
    "name":"Send post",
    "isComplete": true
}

###

DELETE {{TodoApi_HostAddress}}/todoitems/2
X-API-KEY: C2BAECE9CE7748F7

###

GET {{TodoApi_HostAddress}}/todoitems/complete
X-API-KEY: C2BAECE9CE7748F7

###

GET {{TodoApi_HostAddress}}/health

###
